// src/components/shared/Footer.svelte
<div class="border-t border-gray100 mt-24 px-2 xl:px-0">
  <div
    class="flex flex-col xs:flex-row justify-between xs:items-center max-w-7xl mx-auto py-4"
  >
    <div>
      <img class="h-8" src="/logo.png" alt="Bison Drywall logo" />
    </div>
    <div class="flex flex-col xs:flex-row mt-4 xs:mt-0 space-y-4 xs:space-y-0">
      <a
        href="mailto:bisondrywallllc@gmail.com"
        class="mx-0 xs:mx-2 text-sm hover:text-gray700">Contact Us</a
      >
      <a
        href="https://m.facebook.com/bisondrywall"
        class="mx-0 xs:mx-2 text-sm hover:text-gray700">Facebook</a
      >
      <a href="/privacy" class="mx-0 xs:mx-2 text-sm hover:text-gray700"
        >Privacy</a
      >
      <a href="/terms" class="mx-0 xs:mx-2 text-sm hover:text-gray700"
        >Terms of Service</a
      >
    </div>
  </div>
</div>

// src/components/Footer.tsx
import Image from 'next/image';

export default function Footer() {
  return (
    <div className="mt-48 border-t border-gray-600 px-8 xl:px-0">
      <div className="xs:flex-row xs:items-center mx-auto flex max-w-7xl flex-col items-start justify-between py-4">
        <div>
          <Image
            width={47}
            height={20}
            src="/static/images/logo.png"
            alt="Bison Drywall logo"
          />
        </div>
        <div className="xs:mt-0 xs:flex-row xs:space-y-0 xs:space-x-4 mt-4 flex flex-col space-x-0 space-y-4">
          <a
            href="mailto:bisondrywallllc@gmail.com"
            className="xs:mx-2 mx-0 text-xs text-gray-300 hover:text-gray-200"
          >
            Contact Us
          </a>
          <a
            href="https://m.facebook.com/bisondrywall"
            className="xs:mx-2 mx-0 text-xs text-gray-300 hover:text-gray-200"
          >
            Facebook
          </a>
          <a
            href="/privacy"
            className="xs:mx-2 mx-0 text-xs text-gray-300 hover:text-gray-200"
          >
            Privacy
          </a>
          <a
            href="/terms"
            className="xs:mx-2 mx-0 text-xs text-gray-300 hover:text-gray-200"
          >
            Terms of Service
          </a>
        </div>
      </div>
    </div>
  );
}
